export const menuState = {
    loggedIn: false,
    enabled: true,
    strings: {
        about: 'About Firefly',
        generalSettings: 'General Settings',
        security: 'Security',
        advancedSettings: 'Advanced Settings',
        errorLog: 'Error Log',
        diagnostics: 'Diagnostics',
        logout: 'Log Out',
        hide: 'Hide',
        hideOthers: 'Hide Others',
        showAll: 'Show All',
        quit: 'Quit',
        wallet: 'Wallet',
        send: 'Send Funds',
        receive: 'Receive Funds',
        addAccount: 'Add Account',
        help: 'Help',
        troubleshoot: 'Troubleshoot',
        faq: 'FAQ',
        documentation: 'Documentation',
        discord: 'Discord',
        reportAnIssue: 'Report an Issue',
        version: 'Version {version}',
    },
}
